title: LiLAC - A Lightweight Latent ControlNet for Musical Audio Generation
description: Audio Examples
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
